circle/urls.py
from django.urls import path

from . import views

app_name = 'circle'

urlpatterns = [
    path('', views.index, name = 'index'),
    ##광장
    path('gwangjang/', views.gwangjang, name = 'gwangjang'),
    path('gwangjang/<int:question_id>/', views.detail, name = 'detail'),
    path('gwangjang/answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('gwangjang/question/create/', views.question_create, name='question_create'),
    path('gwangjang/question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('gwangjang/question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('gwangjang/answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('gwangjang/answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    path('gwangjang/autonomy_program/',views.autonomy_program, name='autonomy_program'), ##자율프로그램
    path('gwangjang/proposal/',views.proposal, name='proposal'),




    ##동아리 모아보기
    path('circlelist/',views.circle_list, name = 'circle_list'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

facility/urls.py
from django.urls import path
from facility import views

app_name = "facility"

urlpatterns = [
    path('download/', views.downloadFacilities, name='download'),
    path('facilitylist/', views.showFacilities, name='facilitylist'),
    path('facilitylist/getlocation/', views.getlocation, name='location_input'),
    path('showFacilitylist', views.showFacilitylist, name='showFacilitylist'),
    path('showFacilitylist/<int:facility_id>/', views.detail, name='detail'),
]

manam/urls.py
from django.urls import path

from . import views

app_name = 'manam'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('intro/', views.intro, name='intro'),
]

program/urls.py
from django.urls import path

from . import views

app_name = 'program'

urlpatterns = [
    path('', views.index, name='index'),
    path('download/', views.downloadProgram, name='download'),
    path('<int:program_id>/', views.detail, name='detail'),
    path('<int:program_id>/result', views.answer_create, name='result'),
    path('search/', views.program_search, name='search'),
    path('downloadRecommendation/', views.downloadRecommendation, name='downloadRecommendation'),
]

manam/models.py
from django.db import models

# Create your models here.

manam/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'manam/main.html')

def intro(request):
    return render(request,'manam/intro.html')

templates/manam/intro.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<! doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content=""width="device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!-- 폰트 불러오기 -->
    <title>M:ANAM 만남</title>
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    <style>
    @import url(//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css);
    html {
      scroll-behavior: smooth;
    }
    * {
      font-family: 'Spoqa Han Sans Neo', sans-serif;
      }
    header {
      position: sticky;
      padding-top: 70px;
      top: -32px;
      background: #982323;
      color: white;
      padding-left: 32px;
      padding-right: 32px;
      padding-bottom: 5px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.05);
    }
    ul {
      list-style-type: none;
      padding: 0;
    }
    a {
       list-style-type: none;
       font-size: 18px;
       margin-left:16px;
    }
    li {
      display: inline-block;
      margin-left: 16px;
      font-size: 18px;
      color: black;
    }
    .navbar-brand {
      font-size: 40px;
    }
    .intro{
      background: white;
      height: 550px;
      padding-left: 60px;
      padding-top: 30px;
    }
    .shortcut{
      padding-top: 30px;
      /* text-align: center; */
    }
    .container{
      background: white;
      height: 650px;
      display: flex;
      flex-direction: row;
      flex-wrap: nowrap;
      justify-content: space-around;    /* 중심축 */
      align-items: center;  /* cross축 */
    }
    .item{
      width: 350px;
      height: 350px;
      background: #F5F5F5;
      color: black;
      opacity: 1;
      display: flex;
      flex-direction: column;
      justify-content:center;
      align-items:center;
      border-top-left-radius: 60px;
      border-top-right-radius: 60px;
      border-bottom-left-radius: 60px;
      border-bottom-right-radius: 60px;
      box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
      overflow: hidden;
    }
    .select{
      font-weight: Bold;
      font-size: 32px;
      text-align: center;
    }
    .detail{
      font-size: 20px;
      font-weight: Regular;
    }

      body {
        font-family: Consolas, monospace;
      }
      .a {
        letter-spacing: 0px;
        font-size: 32px;
        line-height: 50px;
      }
      .b {
        letter-spacing: 0px;
        word-spacing: 0px;
        font-stretch: condensed;
        line-height: 35px;
      }
      .c {
        letter-spacing: 0px;
        font-size: 18px;
        line-height: 25px;
      }
      .d {
        word-spacing: 0px;
        font-size: 22px;
        line-height: 25px;
        letter-spacing: 0px;
      }
      .e {
        word-spacing: 0px;
      }
      .f {
        word-spacing: 20px;
      }
    </style>
  </head>
    </style>
</head>
<head>
<header>
  <a class="navbar-brand" href="{% url 'manam:index' %}" style="color:white">M:ANAM</a>
  <nav>
      <ul>
          <a class="nav-item" href="{% url 'manam:intro' %}" style="color:white; text-decoration-line : none;" >만남M:ANAM 소개</a>
          <li class="nav-item">
              {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'common:logout' %}" style="color:white">{{ user.username }} (로그아웃)</a>
              {% else %}
              <a class="nav-link" href="{% url 'common:login' %}" style="color:white">로그인</a>
              {% endif %}
          </li>
          <li>
              {% if not user.is_authenticated %}
              <a class="nav-link" href="{% url 'common:signup' %}" style="color:white">회원가입</a>
              {% endif %}
          </li>


    </ul>
  </nav>
</header>

</head>
<body>

<div class="intro">
    <h2 class = "a">📌만남M:ANAM의 역할</h2>
    <h3 class="d">✅추천플랫폼<br> </h3>
    <h4 class="c">위치 기반 성북구 내 문화시설 및 사용자 취향 기반 프로그램 추천 플랫폼<br> </h4>
    <h3 class="d">✅소통플랫폼 <br></h3>
    <h4 class="c">고려대학교 동아리가 성북구 주민과 함께하고 싶은 프로그램 홍보,<br>
    성북구 주민들이 고려대학교 동아리와 함께하고 싶은 프로그램 제안할 수 있는 양방향 소통 플랫폼
    </h4>
    <br>
    <br>
    <h1 class="a"> 📌만남M:ANAM이 향하는 길</h1>
        <h3 class="c">캠퍼스의 가장 큰 사회적 의미는 다양한 관심사를 지니고 그에 대한 열정을 공유하는 학생들에게 만남의 장이 되어준다는 점입니다.
        <br> 이 만남의 장을 통해 학생들은 서로로부터 많은 것들을 느끼고, 배우거나 익히며 발전해 나아갑니다.
        <br> 우리는 만남M:ANAM이라는 새로운 장을 열어, 이러한 캠퍼스의 사회적 가치를 성북구 전반의 분위기로 확장시키고자 합니다.
        <br> 자연어 처리, 추천 알고리즘 등 다양한 최신의 데이터 분석 기법을 적극 활용하여 ‘만남’을 주제로 하여
        <br>여러 문화, 교육 프로그램 및 동아리들에 대한 정보를 제공하고, 소통의 계기를 마련하여 사회적 가치를 실현시키고자 합니다.</h3>
    <br>
    <div class="a" OnClick="location.href ='{% url 'manam:index' %}'" style="cursor:pointer; font-weight:bold;">📌지금 바로 만남 시작하기(CLICK🖱️)
</div>
    <br>
    <br>
</body>
</html>

templates/manam/main.html
{% load static %}
<! doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content=""width="device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!-- 폰트 불러오기 -->
    <title>M:ANAM 만남</title>
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    <style>
    @import url(//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css);
    html {
      scroll-behavior: smooth;
    }
    * {
      font-family: 'Spoqa Han Sans Neo', sans-serif;
      }
    header {
      position: sticky;
      padding-top: 70px;
      top: -32px;
      background: #982323;
      color: white;
      padding-left: 32px;
      padding-right: 32px;
      padding-bottom: 5px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.05);
    }
    ul {
      list-style-type: none;
      padding: 0;
    }
    li {
      display: inline-block;
      margin-left: 16px;
      font-size: 18px;
      color: black;
    }
    .navbar-brand {
      font-size: 40px;
    }
    .intro{
      background: white;
      height: 550px;
      padding-left: 60px;
      padding-top: 30px;
    }
    .shortcut{
      padding-top: 30px;
      /* text-align: center; */
    }
    .container{
      background: white;
      height: 650px;
      display: flex;
      flex-direction: row;
      flex-wrap: nowrap;
      justify-content: space-around;    /* 중심축 */
      align-items: center;  /* cross축 */
    }
    .item{
      width: 350px;
      height: 350px;
      background: #F5F5F5;
      color: black;
      opacity: 1;
      display: flex;
      flex-direction: column;
      justify-content:center;
      align-items:center;
      border-top-left-radius: 60px;
      border-top-right-radius: 60px;
      border-bottom-left-radius: 60px;
      border-bottom-right-radius: 60px;
      box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
      overflow: hidden;
    }
    .select{
      font-weight: Bold;
      font-size: 32px;
      text-align: center;
    }
    .detail{
      font-size: 20px;
      font-weight: Regular;
    }

      body {
        font-family: Consolas, monospace;
      }
      .a {
        letter-spacing: 0px;
        font-size: 32px;
      }
      .b {
        letter-spacing: 0px;
        word-spacing: 2px;
        font-stretch: condensed;
        line-height: 35px
      }
      .c {
        letter-spacing: 0px;
        font-size: 22px;
        line-height: 40px
      }
      .d {
        word-spacing: 0px;
        font-size: 45px;
        line-height: 100px;
        letter-spacing: 2px;
      }
      .e {
        word-spacing: 0px;
      }
      .f {
        word-spacing: 20px;
      }
    </style>
  </head>
    </style>
</head>
<body>
<header>
  <a class="navbar-brand" href="{% url 'manam:index' %}" style="color:white">M:ANAM</a>
  <nav>
      <ul>
          <li class="nav-item">
              {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'common:logout' %}" style="color:white">{{ user.username }} (로그아웃)</a>
              {% else %}
              <a class="nav-link" href="{% url 'common:login' %}" style="color:white">로그인</a>
              {% endif %}
          </li>
          <li>
              {% if not user.is_authenticated %}
              <a class="nav-link" href="{% url 'common:signup' %}" style="color:white">회원가입</a>
              {% endif %}
          </li>
          <li style="color:white">문의사항</li>

    </ul>
  </nav>
</header>
<div class="intro">
    <h1 class = "d">📌만남M:ANAM</h1>
    <h2 class="a">:추천플랫폼➕소통플랫폼
    <h3 class="c">✅추천플랫폼:<br> 위치 기반 성북구 내 문화시설 및 사용자 취향 기반 프로그램 추천 플랫폼<br>
    ✅소통플랫폼: <br>고려대학교 동아리가 성북구 주민과 함께하고 싶은 프로그램 홍보,<br>
    성북구 주민들이 고려대학교 동아리와 함께하고 싶은 프로그램 제안할 수 있는 양방향 소통 플랫폼</h2>
    </h3>
    <br>
    <details class="b">
    <summary class="c"> 만남M:ANAM이 향하는 길</summary>
        캠퍼스의 가장 큰 사회적 의미는 다양한 관심사를 지니고 그에 대한 열정을 공유하는 학생들에게 만남의 장이 되어준다는 점입니다.
        <br> 이 만남의 장을 통해 학생들은 서로로부터 많은 것들을 느끼고, 배우거나 익히며 발전해 나아갑니다.
        <br> 우리는 만남M:ANAM이라는 새로운 장을 열어, 이러한 캠퍼스의 사회적 가치를 성북구 전반의 분위기로 확장시키고자 합니다.
        <br> 자연어 처리, 추천 알고리즘 등 다양한 최신의 데이터 분석 기법을 적극 활용하여 ‘만남’을 주제로 하여
        <br>여러 문화, 교육 프로그램 및 동아리들에 대한 정보를 제공하고, 소통의 계기를 마련하여 사회적 가치를 실현시키고자 합니다.
    </details>
    <br>
    <div class="shortcut" OnClick="location.href = '#menu'" style="cursor:pointer;">
        <h2 class="b">만남 바로 시작하기🏁</h2>
        <i class="fa-solid fa-circle-arrow-right"></i>
    </div>
    <br><br><br><br>
</div>
<br>
    <br>
    <br><br>
<br><br>
<div class="container" id="menu">
    <div class="item item1" OnClick="location.href ='{% url 'facility:facilitylist' %}'" style="cursor:pointer;">
        <div class="select">주변 문화 시설 찾아보기</div>
        <div class="detail">현재 내 주위 이용 가능한 문화 시설</div>

    </div>
    <div class="item item2" OnClick="location.href ='{% url 'program:search' %}'" style="cursor:pointer;">
        <div class="select">맞춤 프로그램 찾아보기</div>
        <div class="detail"><center>빅데이터가 추천해주는 <br>성북구 여가문화 프로그램<center></center></div>
    </div>
    <div class="item item3" OnClick="location.href ='{% url 'circle:index' %}'" style="cursor:pointer;">
        <div class="select">성북구X고려대 M:ANAM</div>
        <div class="detail">고려대 동아리 프로그램 /<br> 성북구 주민 자치 동아리 </div>
    </div>
</div>

</body>
</html>