circle/urls.py
from django.urls import path

from . import views

app_name = 'circle'

urlpatterns = [
    path('', views.index, name = 'index'),
    ##광장
    path('gwangjang/', views.gwangjang, name = 'gwangjang'),
    path('gwangjang/<int:question_id>/', views.detail, name = 'detail'),
    path('gwangjang/answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('gwangjang/question/create/', views.question_create, name='question_create'),
    path('gwangjang/question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('gwangjang/question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('gwangjang/answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('gwangjang/answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    path('gwangjang/autonomy_program/',views.autonomy_program, name='autonomy_program'), ##자율프로그램
    path('gwangjang/proposal/',views.proposal, name='proposal'),




    ##동아리 모아보기
    path('circlelist/',views.circle_list, name = 'circle_list'),
]

circlelist/urls.py
from django.urls import path

from . import views

app_name = 'circlelist'

urlpatterns = [
    path('download/', views.downloadCircle, name='download'),
    path('showcirclelist/<int:circle_id>/', views.detail, name='detail'),
    path('showcirclelist/', views.circle_search, name='search'),
    ]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

kuprogram/urls.py
from django.urls import path

from . import views

app_name = 'kuprogram'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('showprogram/', views.search, name='search'),
    path('showprogram/<int:question_id>/', views.detail, name = 'detail'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
]

manam/urls.py
from django.urls import path

from . import views

app_name = 'manam'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('intro/', views.intro, name='intro'),
]

circle/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    #제목
    subject = models.CharField(max_length = 200)
    #내용
    content = models.TextField()
    #카테고리
    category = models.CharField(max_length=20)
    create_date = models.DateTimeField(null=True,default='')
    modify_date = models.DateTimeField(null=True, blank=True)
    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

circlelist/models.py
from django.db import models

# Create your models here.
class Circle(models.Model):
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    tag = models.CharField(max_length=200)
    content = models.CharField(max_length=200)
    type = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

circle/forms.py
from circle.models import Question, Answer
from django import forms


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'category', 'content']
        labels = {
            'subject': '제목',
            'category': '종류(모집/신청)',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '내용',
        }

circle/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question, Answer
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseNotAllowed


def index(request):
    return render(request, 'circle/circle_main.html')

def circle_list(request):
    return render(request, 'circlelist/circle_search.html')

def gwangjang(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'circle/gwangjang.html', context)


def autonomy_program(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = "모집"
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(category="모집")
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'circle/autonomy_program.html', context)

def proposal(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = "신청"
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(category="신청")
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'circle/proposal.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'circle/question_detail.html', context)

@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('circle:gwangjang')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'circle/question_form.html', context)

@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('circle:detail', question_id=question.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'question': question, 'form': form}
    return render(request, 'circle/question_detail.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정 권한이 없습니다')
        return redirect('circle:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('circle:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'circle/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제 권한이 없습니다')
        return redirect('circle:detail', question_id=question.id)
    question.delete()
    return redirect('circle:gwangjang')

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정 권한이 없습니다')
        return redirect('circle:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('circle:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'circle/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제 권한이 없습니다')
    else:
        answer.delete()
    return redirect('circle:detail', question_id=answer.question.id)

circlelist/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
import pandas as pd
from .models import Circle, Category
from django.core.paginator import Paginator
from django.db.models import Q


def downloadCircle(request):
    filename = 'C:\Korea university\데이터톤\장고\동아리전체데이터.csv'
    df = pd.read_csv(filename, encoding="cp949", na_values='nan')

    category_list = []
    for i in range(len(df)):
        # 프로그램 데이터 db에 저장
        Circle.objects.create(name=df["동아리명"][i],
                              category=df["분과"][i],
                              tag=df["해시태그"][i],
                              content=df["동아리설명"][i],
                              type=df["소속"][i])
        if df["분과"][i] not in category_list:
            Category.objects.create(name=df["분과"][i])
            category_list.append(df["분과"][i])
    return HttpResponse(f'''
    <html>
    <body>
        <h1>카테고리 이름</h1>
        <h1>Download Complete</h1>
        {df}
        <h2>Data Types</h2>
        {df.dtypes}
    </body>
    </html>
    ''')


def detail(request, circle_id):
    circle = get_object_or_404(Circle, pk=circle_id)
    context = {'circle': circle}
    return render(request, 'circlelist/circle_detail.html', context)

def circle_search(request):

    context = {}

    #사이트에서 필터 선택 여부 받아오기
    b = request.GET.get('b', '')
    f = request.GET.getlist('f')
    circle_list = Circle.objects.order_by('name')

    ########## 카테고리 리스트 ###############
    category_list = Category.objects.all()
    context['category_list'] = category_list

    if b:
        circle_list = circle_list.filter(
            Q(name__icontains=b) |
            Q(category__icontains=b) |
            Q(tag__icontains=b) |
            Q(content__icontains=b) |
            Q(type__icontains=b)
        ).distinct()

    if f:
        print(f)
        query = Q()
        for i in f:
            query = query | Q(category__icontains=i)
        circle_list = circle_list.filter(query)


    # 필터링 된 결과 개수
    context['circle_number'] = circle_list.count()

    # 페이징 처리 시작
    page = request.GET.get('page', '1')  # 페이지
    paginator = Paginator(circle_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context['circle_list'] = page_obj

    return render(request, 'circlelist/circle_search.html', context)

templates/circle/autonomy_program.html
{% extends 'base.html' %}
{% load pybo_filter %}
<!-- 네비게이션바 -->
{% block content %}
<script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    <style>
    @import url(//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css);
    html {
      scroll-behavior: smooth;
    }
    * {
      font-family: 'Spoqa Han Sans Neo', sans-serif;
      }
      </style>
<div class="container my-3">
    <div class="row my-100">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse" style="background-color: #982323">
        <div class="sidebar-sticky pt-3" >
          <ul class="nav flex-column">
            <table class = 'table' style="background-color: #000000; color: ##691414">
              <br>
              <thead>
                  <a href="{% url 'circle:autonomy_program' %}" class="btn" style="text-align:left; background-color: #982323; color: white;  font-size:1.5em;" >성북구 어울림</a>

              </thead>
              <br>
              <tbody>
                <!--필터 바-->
                <form class="form-inline my-2 my-md-0" method="get" action="{% url 'circle:gwangjang' %}">
                    <a href="{% url 'circle:question_create' %}" class="btn btn-secondary" >새 글 등록하기</a>
                    <br>
                  <!--검색기능-->
                  <div class="input-group">
                    <input type="text" id="search_kw" placeholder="검색어 입력" class="form-control" value="{{ kw|default_if_none:'' }}">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                    </div>
            </div>  <!--위에것과 기능은 같음-->
                  <!-- <button type='reset' class='btn btn-info'>RESET</button> -->
                </form>
              </tbody>
            </table>

            <br>
            <br>
          </ul>
        </div>
    </nav>

    <role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
        <div class="container">
            <a href="{% url 'circle:gwangjang' %}" class="btn btn-secondary">전체 프로그램</a>
            <a href="{% url 'circle:proposal' %}" class="btn btn-secondary">KU 동아리 프로그램 신청만 보기</a>
            <a href="{% url 'circle:autonomy_program' %}" class="btn btn-success">자율 동아리 모집만 보기</a>
            </div>
        <br>
        <table class="table">
            <thead>
            <tr class="text-center table-dark">
                <th style="width:10%">번호</th>
                <th style="width:30%">제목</th>
                <th style="width:30%">종류(신청/모집)</th>
                <th style="width:10%">작성자</th>
                <th style="width:20%">작성일시</th>
                </tr>
                </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <a href="{% url 'circle:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.category }}</td>
            <td>{{ question.author.username }}</td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">글이 없습니다.</td>
        </tr>
    {% endif %}
    </tbody>
    </table>
    </role>

    <br>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
           <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}"
           href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->

<form id="searchForm" method="get" action="{% url 'circle:gwangjang' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
</div>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

templates/circle/circle_main.html
{% load static %}
<! doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content=""width="device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!-- 폰트 불러오기 -->
    <title>성북구X고려대 M:ANAM</title>
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    <style>
    @import url(//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css);
    html {
      scroll-behavior: smooth;
    }
    * {
      font-family: 'Spoqa Han Sans Neo', sans-serif;
      }
    header {
      position: sticky;
      padding-top: 70px;
      top: -32px;
      background: #982323;
      color: white;
      padding-left: 32px;
      padding-right: 32px;
      padding-bottom: 5px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.05);
    }
    ul {
      list-style-type: none;
      padding: 0;
    }
    li {
      display: inline-block;
      margin-left: 16px;
      font-size: 18px;
      color: black;
    }
    .navbar-brand {
      font-size: 40px;
    }
    .intro{
      background: white;
      height: 550px;
      padding-left: 60px;
      padding-top: 30px;
    }
    .shortcut{
      padding-top: 30px;
      /* text-align: center; */
    }
    .container{
      background: white;
      height: 650px;
      display: flex;
      flex-direction: row;
      flex-wrap: nowrap;
      justify-content: space-around;    /* 중심축 */
      align-items: center;  /* cross축 */
    }
    .item{
      width: 350px;
      height: 350px;
      background: #F5F5F5;
      color: black;
      opacity: 1;
      display: flex;
      flex-direction: column;
      justify-content:center;
      align-items:center;
      border-top-left-radius: 60px;
      border-top-right-radius: 60px;
      border-bottom-left-radius: 60px;
      border-bottom-right-radius: 60px;
      box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
      overflow: hidden;
    }
    .select{
      font-weight: Bold;
      font-size: 32px;
      text-align: center;
    }
    .detail{
      font-size: 20px;
      font-weight: Regular;
    }

    </style>
</head>
<body>
<header>
  <a class="navbar-brand" href="{% url 'circle:index' %}" style="color:white">성북구X고려대 M:ANAM</a>
  <nav>
      <ul>
          <li class="nav-item">
              {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'common:logout' %}" style="color:white">{{ user.username }} (로그아웃)</a>
              {% else %}
              <a class="nav-link" href="{% url 'common:login' %}" style="color:white">로그인</a>
              {% endif %}
          </li>
          <li>
              {% if not user.is_authenticated %}
              <a class="nav-link" href="{% url 'common:signup' %}" style="color:white">회원가입</a>
              {% endif %}

    </ul>
  </nav>
</header>

<div class="container" id="menu">
    <div class="item item1" OnClick="location.href ='{% url 'circle:gwangjang' %}'" style="cursor:pointer;">
        <div class="select">성북 어울림</div>
        <div class="detail">동아리 프로그램 신청 및 자율동아리 모집</div>
    </div>
    <div class="item item2" OnClick="location.href ='{% url 'kuprogram:search' %}'" style="cursor:pointer;">
        <div class="select">KU 어울림</div>
        <div class="detail">고려대학교 동아리 제공 프로그램</div>
    </div>
    <div class="item item3" OnClick="location.href ='{% url 'circlelist:search' %}'" style="cursor:pointer;">
        <div class="select">동아리 모아보기</div>
    </div>
</div>

</body>
</html>

templates/circle/circle_program.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}

templates/circle/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
            {% if request.user == question.author %}
            <a href="{% url 'circle:question_modify' question.id  %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
       data-uri="{% url 'circle:question_delete' question.id  %}">삭제</a>
            {% endif %}
            </div>
        </div>
    </div>
    <!-- 댓글 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 댓글이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
            {% if request.user == answer.author %}
            <a href="{% url 'circle:answer_modify' answer.id  %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary "
               data-uri="{% url 'circle:answer_delete' answer.id  %}">삭제</a>
            {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 댓글 등록 -->
    <form action="{% url 'circle:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">댓글 내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="5"></textarea>
            <br>
        <input type="submit" value="댓글 등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}