common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

manam/urls.py
from django.urls import path

from . import views

app_name = 'manam'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('intro/', views.intro, name='intro'),
]

program/urls.py
from django.urls import path

from . import views

app_name = 'program'

urlpatterns = [
    path('', views.index, name='index'),
    path('download/', views.downloadProgram, name='download'),
    path('<int:program_id>/', views.detail, name='detail'),
    path('<int:program_id>/result', views.answer_create, name='result'),
    path('search/', views.program_search, name='search'),
    path('downloadRecommendation/', views.downloadRecommendation, name='downloadRecommendation'),
]

program/models.py
from django.db import models

# Create your models here.
class Program(models.Model):
    name = models.CharField(max_length=200)
    type = models.CharField(max_length=5)
    category = models.CharField(max_length=10)
    age = models.CharField(max_length=5)
    price = models.IntegerField()
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    host = models.CharField(max_length=20, null=True)
    link = models.CharField(max_length=400, null=True)
    coorx = models.CharField(max_length=30, null=True)
    coory = models.CharField(max_length=30, null=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Recommendation(models.Model):
    name = models.CharField(max_length=200)
    age = models.CharField(max_length=20, null=True)
    rec1 = models.CharField(max_length=200)
    rec2 = models.CharField(max_length=200)
    rec3 = models.CharField(max_length=200)
    rec4 = models.CharField(max_length=200)
    rec1age = models.CharField(max_length=20, null=True)
    rec2age = models.CharField(max_length=20, null=True)
    rec3age = models.CharField(max_length=20, null=True)
    rec4age = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.name

program/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from .models import Program, Category, Recommendation
import pandas as pd
from datetime import datetime
from django.core.paginator import Paginator
from django.db.models import Q

import time


# Create your views here.
def downloadProgram(request):
    filename = 'C:\Korea university\데이터톤\장고\8월전체프로그램.csv'
    df = pd.read_csv(filename, encoding="UTF-8", na_values='nan')
    count = 0
    for i in range(len(df)):
        # 기간 format 변경 (str > date)
        start_date_string = df["행사기간시작일"][i]
        start_date_format = "%Y.%m.%d"
        start_date_result = datetime.strptime(start_date_string, start_date_format)
        end_date_string = df["행사기간종료일"][i]
        end_date_format = "%Y.%m.%d"
        end_date_result = datetime.strptime(end_date_string, end_date_format)
        # 프로그램 데이터 db에 저장
        Program.objects.create(name=df["프로그램명"][i], type=df["유형"][i],
                               category=df["카테고리"][i], host=df["행사시설명"][i], age=df["대상"][i],
                               price=df["수강료"][i], start_date=start_date_result, end_date=end_date_result,
                               link=df["안내URL"][i], coorx=df["X좌표값"][i], coory=df["Y좌표값"][i])
    return HttpResponse(f'''
    <html>
    <body>
        <h1>카테고리 이름</h1>
        <h1>Download Complete</h1>
        {len(df)}
        {count}
        <h2>Data Types</h2>
        {df.dtypes}
    </body>
    </html>
    ''')


def index(request):
    page = request.GET.get('page', '1')  # 페이지
    program_list = Program.objects.order_by('start_date')
    paginator = Paginator(program_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'program_list': page_obj}
    return render(request, 'program/program_list.html', context)  # 객체 있으면 세번째 parameter: context


def detail(request, program_id):
    program = get_object_or_404(Program, pk=program_id)
    context = {}
    context['program'] = program

    # detail의 프로그램에 대한 recommendation 정보 불러오기
    search_name = program.name
    search_age = program.age
    recobj = Recommendation.objects.filter(Q(name=search_name) & Q(age=search_age))
    recobj = recobj.first()

    # 추천 프로그램1
    recommend = Program.objects.filter(Q(name=recobj.rec1) & Q(age=recobj.rec1age)).order_by('-start_date')
    recommend1 = recommend.first()
    context['recommend1'] = recommend1
    # 추천 프로그램2
    recommend = Program.objects.filter(Q(name=recobj.rec2) & Q(age=recobj.rec2age)).order_by('-start_date')
    recommend2 = recommend.first()
    context['recommend2'] = recommend2
    # 추천 프로그램3
    recommend = Program.objects.filter(Q(name=recobj.rec3) & Q(age=recobj.rec3age)).order_by('-start_date')
    recommend3 = recommend.first()
    context['recommend3'] = recommend3
    # 추천 프로그램4
    recommend = Program.objects.filter(Q(name=recobj.rec4) & Q(age=recobj.rec4age)).order_by('-start_date')
    recommend4 = recommend.first()
    context['recommend4'] = recommend4

    return render(request, 'program/program_detail.html', context)


def answer_create(request, program_id):
    program = get_object_or_404(Program, pk=program_id)
    context = {'program': program}
    return render(request, 'program/program_result.html', context)


def program_search(request):
    context = {}

    # 사이트에서 필터 선택 여부 받아오기
    b = request.GET.get('b', '')
    f = request.GET.get('f', '')
    price = request.GET.get('price', '')
    program_list = Program.objects.order_by('-start_date')

    ########## 카테고리 리스트 ###############
    category_list = Category.objects.all()
    context['category_list'] = category_list

    if b:
        program_list = program_list.filter(
            Q(name__icontains=b) |
            Q(category__icontains=b)
        ).distinct()

    if f:
        program_list = program_list.filter(Q(category__icontains=f))

    if price == '0':
        program_list = program_list
    elif price == '1':
        program_list = program_list.filter(price=0)
    elif price == '2':
        program_list = program_list.filter(price__lte=10000)
    elif price == '3':
        program_list = program_list.filter(Q(price__gt=10000) & Q(price__lte=20000))
    elif price == '4':
        program_list = program_list.filter(Q(price__gt=20000) & Q(price__lte=50000))
    elif price == '5':
        program_list = program_list.filter(Q(price__gt=50000) & Q(price__lte=100000))
    elif price == '6':
        program_list = program_list.filter(price__gt=100000)
    else:
        program_list = program_list

    # 필터 옵션
    context['b'] = b
    context['f'] = f
    context['price'] = price

    # 필터링 된 결과 개수
    context['program_number'] = program_list.count()

    # 페이징 처리 시작
    page = request.GET.get('page', '1')  # 페이지
    paginator = Paginator(program_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context['program_list'] = page_obj

    return render(request, 'program/program_search.html', context)


def downloadRecommendation(request):
    filename = 'C:/dataton2022/8월추천프로그램.csv'
    df = pd.read_csv(filename, encoding="UTF-8", na_values='nan')
    list1 = []
    for i in range(len(df)):
        # 추천 데이터 db에 저장
        Recommendation.objects.create(name=df["프로그램명"][i], age=df["대상"][i],
                                      rec1=df["rec_pg1"][i], rec2=df["rec_pg2"][i],
                                      rec3=df["rec_pg3"][i], rec4=df["rec_pg4"][i],
                                      rec1age=df["rec_pg1_대상"][i], rec2age=df["rec_pg2_대상"][i],
                                      rec3age=df["rec_pg3_대상"][i], rec4age=df["rec_pg4_대상"][i])
        list1.append([df["rec_pg1"][i], df["rec_pg2"][i], df["rec_pg3"][i], df["rec_pg4"][i]])
    return HttpResponse(f'''
    <html>
    <body>
    {list1}
    </body>
    </html>
    ''')

templates/program/program_detail.html
{% load static %}
<! doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content=""width="device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
    <script src="https://kit.fontawesome.com/def66b134a.js" crossorigin="anonymous"></script>
    <style>
    @import url(//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css);
    html {
      scroll-behavior: smooth;
    }
    * {
      font-family: 'Spoqa Han Sans Neo', sans-serif;
      }
    header {
      position: sticky;
      padding-top: 20px;
      top: -32px;
      background: white;
      color: black;
      padding-left: 32px;
      padding-right: 32px;
      padding-bottom: 5px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.05);
      z-index:4;
    }
    ul {
      list-style-type: none;
      padding: 0;
    }
    li {
      display: inline-block;
      margin-left: 16px;
      font-size: 18px;
      color: black;
    }
    .navbar-brand {
      font-size: 40px;
    }
    .item{
      width: 300px;
      height: 300px;
      background: #F5F5F5;
      color: black;
      opacity: 1;
      display: flex;
      flex-direction: column;
      justify-content:center;
      align-items:center;
      border-top-left-radius: 50px;
      border-top-right-radius: 50px;
      border-bottom-left-radius: 50px;
      border-bottom-right-radius: 50px;
      box-shadow: 0px 3px 3px rgba(0, 0, 0, 0.25);
      overflow: hidden;
    }
    </style>
</head>
<body>
<!-- 네비게이션바 -->
<header>
  <a class="navbar-brand" href="{% url 'manam:index' %}" style="color:black">M:ANAM</a>
  <nav>
      <ul>
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'program:index' %}" style="color:black">시설</a>
          </li>
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'program:index' %}" style="color:black">프로그램</a>
          </li>
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'program:index' %}" style="color:#982323">KU프로그램</a>
          </li>
          <li class="nav-item">
              {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'common:logout' %}" style="color:grey">{{ user.username }} (로그아웃)</a>
              {% else %}
              <a class="nav-link" href="{% url 'common:login' %}" style="color:grey">로그인</a>
              {% endif %}
          </li>
          <li>
              {% if not user.is_authenticated %}
              <a class="nav-link" href="{% url 'common:signup' %}" style="color:grey">회원가입</a>
              {% endif %}
          </li>
          <li style="color:grey">문의사항</li>

    </ul>
  </nav>
</header>
<!-- 네비게이션바 -->

<div class="container my-3">
    <!-- 프로그램 세부정보 -->
    <h2 class="border-bottom py-2">{{ program.name }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                유형: {{ program.type }}
                카테고리: {{ program.category }}
                연령대: {{ program.age }}
                비용: {{ program.price }}
                시작일: {{ program.start_date }}
                종료일: {{ program.end_date }}
                기관: {{ program.host }}
                {% if program.link %}
                신청링크: <a href = {{ program.link }}> {{ program.link }} </a>
                {% else %}
                신청링크: 제공되지 않습니다
                {% endif %}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ program.category }}</div>
                    <div>{{ program.age }}</div>
                </div>
            </div>
        </div>
    </div>
    <div class="card my-3" style="background-color: #F5F5F5;">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                <h4>이런 프로그램은 어때요?</h4>
                <div class="container" style="display: flex; flex-direction: row; flex-wrap: nowrap; justify-content:space-around; align-items: center;">
                    <div class="item item1" OnClick="location.href ='{% url 'program:detail' recommend1.id %}'" style="cursor:pointer;">
                        <div class="select" style="text-align:center; font-weight:bold;">{{ recommend1.name }}</div>
                        <div class="detail">{{ recommend1.category}}</div>
                    </div>
                    <div class="item item2" OnClick="location.href ='{% url 'program:detail' recommend2.id %}'" style="cursor:pointer;">
                        <div class="select" style="text-align:center; font-weight:bold;">{{ recommend2.name }}</div>
                        <div class="detail">{{ recommend2.category}}</div>
                    </div>
                    <div class="item item3" OnClick="location.href ='{% url 'program:detail' recommend3.id %}'" style="cursor:pointer;">
                        <div class="select" style="text-align:center; font-weight:bold;">{{ recommend3.name }}</div>
                        <div class="detail">{{ recommend3.category}}</div>
                    </div>
                    <div class="item item4" OnClick="location.href ='{% url 'program:detail' recommend4.id %}'" style="cursor:pointer;">
                        <div class="select" style="text-align:center; font-weight:bold;">{{ recommend4.name }}</div>
                        <div class="detail">{{ recommend4.category}}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/program/program_list.html
{% extends 'base.html' %}
{% block style %}
    .h3 {
      text-align:center
    }
{% endblock %}
{% block content %}
    <div class="table-title">
        <h3>맞춤 프로그램 찾아보기</h3>
    </div>
    <div class="container my-3">
        <table class="table">
            <thead>
            <tr class="table-dark">
                <th>프로그램명</th>
                <th>유형</th>
                <th>카테고리</th>
                <th>연령대</th>
                <th>비용</th>
                <th>기간시작</th>
                <th>기간끝</th>
                <th>기관</th>
            </tr>
            </thead>
            <tbody>
            {% if program_list %}
            {% for program in program_list %}
            <tr class="text-center">
                <td class="text-start">
                    <a href="{% url 'program:detail' program.id %}">{{ program.name }}</a>
                </td>
                <td>{{ program.type }}</td>
                <td>{{ program.category }}</td>
                <td>{{ program.age }}</td>
                <td>{{ program.price }}</td>
                <td>{{ program.start_date }}</td>
                <td>{{ program.end_date }}</td>
                <td>{{ program.host }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="4">질문이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if program_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ program_list.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in program_list.paginator.page_range %}
            {% if page_number >= program_list.number|add:-5 and page_number <= program_list.number|add:5 %}
            {% if page_number == program_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
            {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if program_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ program_list.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
    </div>
{% endblock %}

templates/program/program_search.html
{% extends 'base.html' %}

{% block title %} 검색 결과 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse" style="background-color: #982323">
        <div class="sidebar-sticky pt-3">
          <ul class="nav flex-column">
            <table class = 'table' style="background-color: #000000; color: ##691414">
              <thead>
                  <table class = 'table' style="background-color: #000000; color: ##691414">
              <thead>
                  <a href="{% url 'program:search' %}" class="btn" style="text-align:left; background-color: #982323; color: white;  font-size:1.5em" >프로그램 찾기</a>
              </thead>
              <tbody>
                <!--필터 바-->
                <form class="form-inline my-2 my-md-0" method="get" action="{% url 'program:search' %}">
                  <!--검색기능-->
                  <input class="form-control" type="text" placeholder="프로그램 검색" aria-label="Search" name="b" value="{{b}}">

                  <div style="line-height:170%; color:grey">
                      <label for="customRange3" style="color: #CDCDCD">현재 결과<br>
                      </label>
                      <br>
                      카테고리 |
                      {% if f %}
                      {{ f }}
                      {% else %}
                      전체
                      {% endif %}
                  </div>
                  <div style="line-height:170%; color:grey">
                      가격 |
                      {% if price == '0' %}
                      전체
                      {% elif price == '1' %}
                      무료
                      {% elif price == '2' %}
                      ~10,000원
                      {% elif price == '3' %}
                      10,001원~20,000원
                      {% elif price == '4' %}
                      20,001원~50,000원
                      {% elif price == '5' %}
                      50,001원~100,000원
                      {% elif price == '6' %}
                      100,001원~
                      {% else %}
                      전체
                      {% endif %}
                    </div>
                  <!--카테고리필터-->
                  <label for="customRange3" style="color: #CDCDCD">카테고리</label>

                  <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" id="customRadio1" name="f", value="생활교양">
                      <label class="form-check-label" for="customRadio1" style="color: white">생활교양</label>
                  </div>
                  <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" id="customRadio2" name="f", value="행사">
                      <label class="form-check-label" for="customRadio2" style="color: white">행사</label>
                  </div>
                  <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" id="customRadio3" name="f", value="미술">
                      <label class="form-check-label" for="customRadio3" style="color: white">미술</label>
                  </div>
                  <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" id="customRadio4" name="f", value="미디어">
                      <label class="form-check-label" for="customRadio4" style="color: white">미디어</label>
                  </div>
                  <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" id="customRadio5" name="f", value="음악">
                      <label class="form-check-label" for="customRadio5" style="color: white">음악</label>
                  </div>
                  <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" id="customRadio6" name="f", value="공예">
                      <label class="form-check-label" for="customRadio6" style="color: white">공예</label>
                  </div>
                  <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" id="customRadio7" name="f", value="운동">
                      <label class="form-check-label" for="customRadio7" style="color: white">운동</label>
                  </div>
                  <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" id="customRadio8" name="f", value="공연">
                      <label class="form-check-label" for="customRadio8" style="color: white">공연</label>
                  </div>
                  <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" id="customRadio9" name="f", value="무용">
                      <label class="form-check-label" for="customRadio9" style="color: white">무용</label>
                  </div>
                  <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" id="customRadio10" name="f", value="사회활동">
                      <label class="form-check-label" for="customRadio10" style="color: white">사회활동</label>
                  </div>
                  <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" id="customRadio11" name="f", value="문학">
                      <label class="form-check-label" for="customRadio11" style="color: white">문학</label>
                  </div>


                  <!--가격필터-->
                  <div class="form-group">
                    <a href = "#" onclick= "event.stopPropagation()"></a>
                    <label for="customRange3" style="color: #CDCDCD">가격 범위</label>

                    <select source="[name=price]">
                      <option value="0">전체</option>
                      <option value="1">무료</option>
                      <option value="2">~10,000원</option>
                      <option value="3">10,001원~20,000원</option>
                      <option value="4">20,001원~50,000원</option>
                      <option value="5">50,001원~100,000원</option>
                      <option value="6">100,001원~</option>
                    </select>

                    <input type="range" class="custom-range" value = "0" min="0" max="6" step="1" id="customRange3" name="price", value={{price}}>

                  </div>
                  <button type='submit' class='btn btn-warning' style="background-color:#ebc291">검색</button>  <!--위에것과 기능은 같음-->
                  <!-- <button type='reset' class='btn btn-info'>RESET</button> -->
                </form>
              </tbody>
            </table>

            <br>
            <br>
          </ul>
        </div>
      </nav>
      <role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
        <br>총 <b>{{ program_number }}</b>개의 프로그램
        <table class="table">
            <thead>
            <tr class="table-dark">
                <th>프로그램명</th>
                <th>카테고리</th>
                <th>연령대</th>
                <th>비용</th>
                <th>시작일</th>
                <th>종료일</th>
            </tr>
            </thead>
            <tbody>
            {% if program_list %}
            {% for program in program_list %}
            <tr class="text-center">
                <td class="text-start">
                    <a href="{% url 'program:detail' program.id %}" style="text-decoration:none; color:black;">{{ program.name }}</a>
                </td>
                <td>{{ program.category }}</td>
                <td>{{ program.age }}</td>
                <td>{{ program.price }}</td>
                <td>{{ program.start_date }}</td>
                <td>{{ program.end_date }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="4">프로그램이 없습니다.</td>
            </tr>
        {% endif %}
        </tbody>
        </table>
        </role>

        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if program_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?b={{request.GET.b}}&f={{request.GET.f}}&price={{request.GET.price}}&page={{ program_list.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in program_list.paginator.page_range %}
            {% if page_number >= program_list.number|add:-5 and page_number <= program_list.number|add:5 %}
            {% if page_number == program_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?b={{request.GET.b}}&f={{request.GET.f}}&price={{request.GET.price}}&page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?b={{request.GET.b}}&f={{request.GET.f}}&price={{request.GET.price}}&page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
            {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if program_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?b={{request.GET.b}}&f={{request.GET.f}}&price={{request.GET.price}}&page={{ program_list.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
    </div>



</div>

<!--프로그램가격필터 바의 위치에 따라 가격이 실시간으로 표시되게 하는 자바스크립트-->
<script>
      ;(function(){

      function emit(target, name) {
        var event
        if (document.createEvent) {
          event = document.createEvent("HTMLEvents");
          event.initEvent(name, true, true);
        } else {
          event = document.createEventObject();
          event.eventType = name;
        }

        event.eventName = name;

        if (document.createEvent) {
          target.dispatchEvent(event);
        } else {
          target.fireEvent("on" + event.eventType, event);
        }
      }

      var outputsSelector = "input[type=number][source],select[source]";

      function onChange(e) {
        var outputs = document.querySelectorAll(outputsSelector)
        for (var index = 0; index < outputs.length; index++) {
          var item = outputs[index]
          var source = document.querySelector(item.getAttribute('source'));
          if (source) {
            if (item === e.target) {
              source.value = item.value
              emit(source, 'input')
              emit(source, 'change')
            }

            if (source === e.target) {
              item.value = source.value
            }
          }
        }
      }

      document.addEventListener('change', onChange)
      document.addEventListener('input', onChange)
    }());


</script>
{% endblock %}