circle/urls.py
from django.urls import path

from . import views

app_name = 'circle'

urlpatterns = [
    path('', views.index, name = 'index'),
    ##광장
    path('gwangjang/', views.gwangjang, name = 'gwangjang'),
    path('gwangjang/<int:question_id>/', views.detail, name = 'detail'),
    path('gwangjang/answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('gwangjang/question/create/', views.question_create, name='question_create'),
    path('gwangjang/question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('gwangjang/question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('gwangjang/answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('gwangjang/answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    path('gwangjang/autonomy_program/',views.autonomy_program, name='autonomy_program'), ##자율프로그램
    path('gwangjang/proposal/',views.proposal, name='proposal'),




    ##동아리 모아보기
    path('circlelist/',views.circle_list, name = 'circle_list'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

facility/urls.py
from django.urls import path
from facility import views

app_name = "facility"

urlpatterns = [
    path('download/', views.downloadFacilities, name='download'),
    path('facilitylist/', views.showFacilities, name='facilitylist'),
    path('facilitylist/getlocation/', views.getlocation, name='location_input'),
    path('showFacilitylist', views.showFacilitylist, name='showFacilitylist'),
    path('showFacilitylist/<int:facility_id>/', views.detail, name='detail'),
]

manam/urls.py
from django.urls import path

from . import views

app_name = 'manam'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('intro/', views.intro, name='intro'),
]

program/urls.py
from django.urls import path

from . import views

app_name = 'program'

urlpatterns = [
    path('', views.index, name='index'),
    path('download/', views.downloadProgram, name='download'),
    path('<int:program_id>/', views.detail, name='detail'),
    path('<int:program_id>/result', views.answer_create, name='result'),
    path('search/', views.program_search, name='search'),
    path('downloadRecommendation/', views.downloadRecommendation, name='downloadRecommendation'),
]

facility/models.py
from django.db import models

# Create your models here.
class Facility(models.Model):
    cate_1 = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    lat = models.CharField(max_length=50)
    lng = models.CharField(max_length=50)
    dong = models.CharField(max_length=50)
    cate_2 = models.CharField(max_length=50)
    content = models.TextField()
    url = models.CharField(max_length=500)

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

facility/forms.py
from django import forms

class NameForm(forms.Form):
    your_name = forms.CharField(label='location_input', max_length=100)

facility/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
import pandas as pd
from .models import Facility, Category
import json
from django.core.paginator import Paginator
from django.db.models import Q


# Create your views here.
def map(request):
    return render(request, 'facility/test.html')

def downloadFacilities(request):
    with open('C:\Korea university\데이터톤\장고\전체시설정보.json', encoding='utf-8') as json_file:
        facility = json.load(json_file)
        category_list = []

        for i in range(len(facility)):
            Facility.objects.create(
                cate_1 = facility[i]['구분'],
                name = facility[i]['시설명'],
                lat = facility[i]['lat'],
                lng = facility[i]['lng'],
                dong = facility[i]['행정동'],
                cate_2 = facility[i]['분류체계'],
                content = facility[i]['시설정보'],
                url = facility[i]['링크']
            )
            if facility[i]["구분"] not in category_list:
                Category.objects.create(name=facility[i]["구분"])
                category_list.append(facility[i]["구분"])

    return HttpResponse(f'''
        <html>
        <body>
            <h1>Download Complete</h1>
            {facility}
        </body>
        </html>
        ''')


def showFacilities(request):
    facilities = Facility.objects.all
    context = {'facilities': facilities}
    return render(request, 'facility/default.html', context)


def getlocation(request):
    location_input = request.GET.get('location_input', '')
    facilities = Facility.objects.all
    context = {'facilities': facilities, 'location_input': location_input}
    return render(request, 'facility/get_location.html', context)

def showFacilitylist(request):
        context = {}
        facility_list = Facility.objects.order_by('name')

        # 사이트에서 필터 선택 여부 받아오기
        b = request.GET.get('b', '')
        price = request.GET.get('price', '')
        print(price)

        ########## 카테고리 리스트 ###############
        category_list = Category.objects.all()
        context['category_list'] = category_list

        if b:
            facility_list = facility_list.filter(
                Q(name__icontains=b) |
                Q(cate_1__icontains=b) |
                Q(cate_2__icontains=b) |
                Q(dong__icontains=b) |
                Q(content__icontains=b)
            ).distinct()

        if price == '0':
            facility_list = facility_list
        elif price == '1':
            facility_list = facility_list.filter(cate_1= '공공도서관')
        elif price == '2':
            facility_list = facility_list.filter(cate_1= '공공체육시설')
        elif price == '3':
            facility_list = facility_list.filter(cate_1= '공연장')
        elif price == '4':
            facility_list = facility_list.filter(cate_1= '교육기관')
        elif price == '5':
            facility_list = facility_list.filter(cate_1= '도서관')
        elif price == '6':
            facility_list = facility_list.filter(cate_1= '동주민센터')
        elif price == '7':
            facility_list = facility_list.filter(cate_1= '문화시설')
        elif price == '8':
            facility_list = facility_list.filter(cate_1= '문화예술회관')
        elif price == '9':
            facility_list = facility_list.filter(cate_1= '문화원')
        elif price == '10':
            facility_list = facility_list.filter(cate_1= '미술관')
        elif price == '11':
            facility_list = facility_list.filter(cate_1= '박물관/기념관')
        elif price == '12':
            facility_list = facility_list.filter(cate_1= '아동청소년지원센터')
        elif price == '13':
            facility_list = facility_list.filter(cate_1= '작은도서관')
        elif price == '14':
            facility_list = facility_list.filter(cate_1= '노인복지시설(경로당)')
        elif price == '15':
            facility_list = facility_list.filter(cate_1= '노인여가복지시설')
        elif price == '16':
            facility_list = facility_list.filter(cate_1= '노인의료복지시설(노인요양공동생활가정)')
        elif price == '17':
            facility_list = facility_list.filter(cate_1= '노인의료복지시설(노인요양시설)')
        elif price == '18':
            facility_list = facility_list.filter(cate_1= '노인주거복지시설')
        elif price == '19':
            facility_list = facility_list.filter(cate_1= '재가노인복지시설(재가노인지원)')
        elif price == '20':
            facility_list = facility_list.filter(cate_1= '재가노인복지시설(주야간보호)')
        elif price == '21':
            facility_list = facility_list.filter(cate_1= '방과후교실')
        elif price == '22':
            facility_list = facility_list.filter(cate_1= '지역아동센터')
        elif price == '23':
            facility_list = facility_list.filter(cate_1= '틈새돌봄기관')
        elif price == '24':
            facility_list = facility_list.filter(cate_1= '거주시설')
        elif price == '25':
            facility_list = facility_list.filter(cate_1= '공동생활가정')
        elif price == '26':
            facility_list = facility_list.filter(cate_1= '단기거주시설')
        elif price == '27':
            facility_list = facility_list.filter(cate_1= '복지관1')
        elif price == '28':
            facility_list = facility_list.filter(cate_1= '복지관2')
        elif price == '29':
            facility_list = facility_list.filter(cate_1= '지역사회재활시설')
        elif price == '30':
            facility_list = facility_list.filter(cate_1= '직업재활시설')
        elif price == '31':
            facility_list = facility_list.filter(cate_1= '기타')
        elif price == '32':
            facility_list = facility_list.filter(cate_2= '교육·문화')
        elif price == '33':
            facility_list = facility_list.filter(cate_2= '노인·청소년')
        elif price == '34':
            facility_list = facility_list.filter(cate_2= '보육·가족및여성')
        elif price == '35':
            facility_list = facility_list.filter(cate_2= '사회복지일반')
        else:
            facility_list = facility_list

            # 필터 옵션
        context['b'] = b
        context['price'] = price

        # 필터링 된 결과 개수
        context['facility_number'] = facility_list.count()

        # 페이징 처리 시작
        page = request.GET.get('page', '1')  # 페이지
        paginator = Paginator(facility_list, 10)  # 페이지당 10개씩 보여주기
        page_obj = paginator.get_page(page)
        context['facility_list'] = page_obj

        return render(request, 'facility/facility_list.html', context)


def detail(request, facility_id):
    facility = get_object_or_404(Facility, pk=facility_id)
    context = {'facility': facility}
    return render(request, 'facility/facility_detail.html', context)

templates/facility/default.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content=""width="device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
    <script src="https://kit.fontawesome.com/def66b134a.js" crossorigin="anonymous"></script>
    <style>
    @import url(//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css);
    html {
      scroll-behavior: smooth;
    }
    * {
      font-family: 'Spoqa Han Sans Neo', sans-serif;
      }


    .v2_35 {
    width: 700px;
    height: 65px;
    background: rgba(245,245,245,1);
    opacity: 1;
    position: relative;
    top: 10px;
    left: 360px;
    border-top-left-radius: 13px;
    border-top-right-radius: 13px;
    border-bottom-left-radius: 13px;
    border-bottom-right-radius: 13px;
    }
    .v30_9 {
    width: 500px;
    color: rgba(0,0,0,1);
    position: absolute;
    top: 105px;
    left: 500px;
    font-family: Inter;
    font-weight: Bold;
    font-size: 40px;
    opacity: 1;
    text-align: left;
    }
    div > form{
    width:500px;
    height:50px;
    left: 710px;
    position:relative;
    top : -350px;
    }
    #map {
    width:800px;
    height:400px;
    position:relative;
    top : 90px;
    left: 310px;
    }
    p {
    position:relative;
    left: 570px;
    top: -5px;
    }
    header {
      position: sticky;
      padding-top: 20px;
      top: -32px;
      background: white;
      color: black;
      padding-left: 32px;
      padding-right: 32px;
      padding-bottom: 5px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.05);
    }
    ul {
      list-style-type: none;
      padding: 0;
    }
    li {
      display: inline-block;
      margin-left: 16px;
      font-size: 18px;
      color: black;
    }
    .navbar-brand {
      font-size: 40px;
    }

    .wrap {position: absolute;left: 0;bottom: 40px;width: 270px;height: 132px;margin-left: -144px;text-align: left;overflow: hidden;font-size: 12px;font-family: 'Malgun Gothic', dotum, '돋움', sans-serif;line-height: 1.5;}
    .wrap * {padding: 0;margin: 0;}
    .wrap .info {width: 286px;height: 120px;border-radius: 5px;border-bottom: 2px solid #ccc;border-right: 1px solid #ccc;overflow: hidden;background: #fff;}
    .wrap .info:nth-child(1) {border: 0;box-shadow: 0px 1px 2px #888;}
    .info .title {padding: 5px 0 0 10px;height: 30px;background: #eee;border-bottom: 1px solid #ddd;font-size: 18px;font-weight: bold;}
    .info .close {position: absolute;top: 10px;right: 10px;color: #888;width: 17px;height: 17px;background: url('https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/overlay_close.png');}
    .info .close:hover {cursor: pointer;}
    .info .body {position: relative;overflow: hidden;}
    .info .desc {position: relative;right:75px;margin: 13px 0 0 90px;height: 75px;}
    .desc .ellipsis {overflow: hidden;text-overflow: ellipsis;white-space: nowrap;}
    .desc .jibun {font-size: 11px;color: #888;margin-top: -2px;}
    .info .link {color: #5085BB;}



</style>
</head>
<body>
<!-- 네비게이션바 -->
<header>
  <a class="navbar-brand" href="{% url 'manam:index' %}" style="color:black">M:ANAM</a>
  <nav>
      <ul>
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'facility:facilitylist' %}" style="color:black">시설</a>
          </li>
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'program:search' %}" style="color:black">프로그램</a>
          </li>
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'circle:index' %}" style="color:#982323">KU프로그램</a>
          </li>
          <li class="nav-item">
              {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'common:logout' %}" style="color:grey">{{ user.username }} (로그아웃)</a>
              {% else %}
              <a class="nav-link" href="{% url 'common:login' %}" style="color:grey">로그인</a>
              {% endif %}
          </li>
          <li>
              {% if not user.is_authenticated %}
              <a class="nav-link" href="{% url 'common:signup' %}" style="color:grey">회원가입</a>
              {% endif %}
          </li>

    </ul>
  </nav>
</header>

    <div class="v2_35"></div>
    <div class="v30_9">나의 위치는 어디인가요?</div>
    <div id="map" ></div>

    <div id="lat" style="display: none">
        {% for fa in facilities %}
            {{fa.lat}},
        {% endfor %}
    </div>
    <div id="lng" style="display: none">
        {%for fa in facilities%}
            {{fa.lng}},
        {% endfor %}
    </div>
    <div id="name" style="display: none">
        {%for fa in facilities%}
            {{fa.name}},
        {% endfor %}
    </div>
     <div id="cate" style="display: none">
        {%for fa in facilities%}
            {{fa.cate_1}},
        {% endfor %}
    </div>
     <div id="url" style="display: none">
        {%for fa in facilities%}
            {{fa.url}},
        {% endfor %}
    </div>

<div>
<!-- 조회폼 -->
    <form action="{% url 'facility:location_input' %}" method="get">
    {% csrf_token %}
    <label for="location_input"> 위치조회 </label>
    <input type="text" name="location_input" value="{{ location_input }}" id="location_input">
    <input type="submit" value="해당주소로 지도 이동">
    </form>
</div>

<a href="{% url 'facility:showFacilitylist' %}" class="delete btn btn-sm btn-outline-success" style="position:relative;top:-500px;left:1200px;">전체시설목록 보러가기</a>

<div style="position:relative;top:-460px;left:490px;"> * 위치접근 허용을 해주시면 현재 내 위치 주변으로 지도가 이동합니다 :)</div>
<p>
    <input type="checkbox" id="chkTraffic" onclick="setOverlayMapTypeId()" /> 교통정보 보기
    <input type="checkbox" id="chkBicycle" onclick="setOverlayMapTypeId()" /> 자전거도로 정보 보기
    <input type="checkbox" id="chkUseDistrict" onclick="setOverlayMapTypeId()" /> 지적편집도 정보 보기
    <input type="checkbox" id="chkTerrain" onclick="setOverlayMapTypeId()" /> 지형정보 보기
    </p>

    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=3464eb8d032a6121616cba7859e41673&libraries=service,clusterer,drawing"></script>
    <script>
        var container = document.getElementById('map');
        var options = {
            center: new kakao.maps.LatLng(37.58641690228, 127.02918113964),
            level: 3
        };

        var map = new kakao.maps.Map(container,options);

        var list_lat = document.getElementById("lat").innerText.split(',');
        var list_lng = document.getElementById("lng").innerText.split(',');
        var list_name = document.getElementById("name").innerText.split(',');
        var list_cate = document.getElementById("cate").innerText.split(',');
        var list_url = document.getElementById("url").innerText.split(',');

        var facilityCoordinates = [];

        for(var idx=0; idx<list_lat.length;idx++){
            var content = {
                latlng : new kakao.maps.LatLng(list_lat[idx],list_lng[idx]),
                name : list_name[idx],
                cate : list_cate[idx],
                url : list_url[idx],
            }
            facilityCoordinates.push(content);
            };
            console.log(facilityCoordinates);



        for(var idx=0; idx<facilityCoordinates.length;idx++){
            var marker = new kakao.maps.Marker({
            map: map,
            position: facilityCoordinates[idx].latlng,
            title: facilityCoordinates[idx].name
            });

            (function(marker, place) {

                kakao.maps.event.addListener(marker, 'click', function() {
                    var overlay = new kakao.maps.CustomOverlay({
                        content: '<div class="wrap">' +
                                '    <div class="info">' +
                                '        <div class="title">' +
                                            place.name +
                                '            <div class="close" onclick= "closeOverlay()" title="닫기"></div> '+
                                '        </div>' +
                                '        <div class="body">' +
                                '            <div class="desc">' +
                                '                <div class="cate">' +  place.cate  +'</div>' +
                                '                  <div> 시설 홈페이지: </div>' +
                                '		         <div><a href= ' + place.url +  ' target="_blank">' + place.url + '</a></div>' +
                                '            </div>' +
                                '        </div>' +
                                '    </div>' +
                                '</div>',
                        map: map,
                        position: marker.getPosition()

                        });


                    console.log(overlay);
                    overlay.setMap(map);

                    function closeOverlay() {
                        overlay.setMap(null);
                    }
                    })

                })(marker, facilityCoordinates[idx]);

            }


        // HTML5의 geolocation으로 사용할 수 있는지 확인합니다
        if (navigator.geolocation) {

            // GeoLocation을 이용해서 접속 위치를 얻어옵니다
            navigator.geolocation.getCurrentPosition(function(position) {

                var lat = position.coords.latitude, // 위도
                    lon = position.coords.longitude; // 경도

                var locPosition = new kakao.maps.LatLng(lat, lon), // 마커가 표시될 위치를 geolocation으로 얻어온 좌표로 생성합니다
                    message = '<div style="padding:5px;">현재 내 위치</div>'; // 인포윈도우에 표시될 내용입니다

                // 마커와 인포윈도우를 표시합니다
                displayMarker(locPosition, message);

            });

        } else { // HTML5의 GeoLocation을 사용할 수 없을때 마커 표시 위치와 인포윈도우 내용을 설정합니다

            var locPosition = new kakao.maps.LatLng(37.58641690228, 127.02918113964),
                message = 'geolocation을 사용할수 없어요..'

            displayMarker(locPosition, message);
        }

        // 지도에 마커와 인포윈도우를 표시하는 함수입니다
        function displayMarker(locPosition, message) {
            var imageSrc = "https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png";

            // 마커 이미지의 이미지 크기 입니다
            var imageSize = new kakao.maps.Size(24, 35);

            // 마커 이미지를 생성합니다
            var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize);

            // 마커를 생성합니다
            var marker = new kakao.maps.Marker({
                map: map, // 마커를 표시할 지도
                position: locPosition, // 마커를 표시할 위치
                image : markerImage, // 마커 이미지
                text: message
            });

            var iwContent = message, // 인포윈도우에 표시할 내용
                iwRemoveable = true;

            // 인포윈도우를 생성합니다
            var infowindow = new kakao.maps.InfoWindow({
                content : iwContent,
                removable : iwRemoveable
            });

            // 인포윈도우를 마커위에 표시합니다
            infowindow.open(map, marker);

            // 지도 중심좌표를 접속위치로 변경합니다
            map.setCenter(locPosition);
        }

var mapTypes = {
    terrain : kakao.maps.MapTypeId.TERRAIN,
    traffic :  kakao.maps.MapTypeId.TRAFFIC,
    bicycle : kakao.maps.MapTypeId.BICYCLE,
    useDistrict : kakao.maps.MapTypeId.USE_DISTRICT
};

// 체크 박스를 선택하면 호출되는 함수입니다
function setOverlayMapTypeId() {
    var chkTerrain = document.getElementById('chkTerrain'),
        chkTraffic = document.getElementById('chkTraffic'),
        chkBicycle = document.getElementById('chkBicycle'),
        chkUseDistrict = document.getElementById('chkUseDistrict');

    // 지도 타입을 제거합니다
    for (var type in mapTypes) {
        map.removeOverlayMapTypeId(mapTypes[type]);
    }

    // 지적편집도정보 체크박스가 체크되어있으면 지도에 지적편집도정보 지도타입을 추가합니다
    if (chkUseDistrict.checked) {
        map.addOverlayMapTypeId(mapTypes.useDistrict);
    }

    // 지형정보 체크박스가 체크되어있으면 지도에 지형정보 지도타입을 추가합니다
    if (chkTerrain.checked) {
        map.addOverlayMapTypeId(mapTypes.terrain);
    }

    // 교통정보 체크박스가 체크되어있으면 지도에 교통정보 지도타입을 추가합니다
    if (chkTraffic.checked) {
        map.addOverlayMapTypeId(mapTypes.traffic);
    }

    // 자전거도로정보 체크박스가 체크되어있으면 지도에 자전거도로정보 지도타입을 추가합니다
    if (chkBicycle.checked) {
        map.addOverlayMapTypeId(mapTypes.bicycle);
    }

}

    </script>
<div> {{ facilityCoordinates }} </div>
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/facility/facility_detail.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'facility:showFacilitylist' %}" class="delete btn btn-sm btn-outline-success" style="position:relative;top:65px;left:1100px;">전체시설목록</a>
<div class="container my-3">
    <!-- 시설 세부정보 -->
    <h2 class="border-bottom py-2">{{ facility.name }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                <구분>
                {{ facility.cate_1 }}

                <행정동>
                {{ facility.dong }}

                <분류체계>
                {{ facility.cate_2 }}

                <시설정보>
                {{ facility.content }}

                <홈페이지>
                <a href= "{{ facility.url }}" > {{ facility.url }}</a>
            </div>

        </div>
    </div>
</div>
{% endblock %}